# Generated by Django 5.2.6 on 2026-10-01 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=160)),
                ('industry', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=80)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_role', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('employee_count', models.PositiveIntegerField(default=50)),
                ('existing_fleet_size', models.PositiveIntegerField(default=10)),
                ('estimated_ev_requirement', models.PositiveIntegerField(default=5)),
                ('monthly_km_per_vehicle', models.PositiveIntegerField(default=1500)),
                ('budget_per_vehicle', models.DecimalField(decimal_places=2, default=160000, max_digits=12)),
                ('purchase_timeline', models.CharField(default='1-3 Months', max_length=50)),
                ('authority', models.CharField(default='Influencer', max_length=50)),
                ('source', models.CharField(default='Lead Discovery Agent', max_length=80)),
                ('research_summary', models.TextField(blank=True)),
                ('fit_score', models.FloatField(default=50)),
                ('dynamic_score', models.FloatField(default=30)),
                ('conversion_probability', models.FloatField(default=20)),
                ('stage', models.CharField(choices=[('Cold', 'Cold'), ('Qualified', 'Qualified'), ('Warm', 'Warm'), ('Hot', 'Hot'), ('Converted', 'Converted')], default='Cold', max_length=20)),
                ('next_best_action', models.CharField(default='Research company', max_length=200)),
                ('next_action_reason', models.TextField(blank=True)),
                ('converted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('range_km', models.PositiveIntegerField()),
                ('payload_kg', models.PositiveIntegerField(default=100)),
                ('best_for', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('email_open', 'Email Opened'), ('pricing_click', 'Pricing Link Clicked'), ('product_view', 'Product Viewed'), ('brochure', 'Brochure Downloaded'), ('whatsapp_reply', 'WhatsApp Replied'), ('quote', 'Quotation Requested'), ('demo', 'Demo Requested'), ('no_response', 'No Response / Decay'), ('not_interested', 'Not Interested')], max_length=40)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sales.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.FloatField()),
                ('new_score', models.FloatField()),
                ('reason', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='sales.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='Email', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach', to='sales.lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='recommended_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.product'),
        ),
    ]
